language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- chmod +x gradlew
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
after_success:
- chmod +x ./generate-apk-release.sh
- "./generate-apk-release.sh"
script:
- cd $TRAVIS_BUILD_DIR/
- "./gradlew assembleDebug"
notifications:
  email: false
  slack:
    rooms:
    - mymartlet:oLnKxWZuf6ZPhA6zAfRIArWI#travis
    on_success: always
    on_failure: always
    template:
    - "MyMartlet Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) %{result} in %{duration}"
    - "%{commit_subject}"
    - "<https://github.com/jguerinet/MyMartlet-APK/releases/tag/v%{build_number}|APK Download>"
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: PMIfJko7rz/aacy5Vc1v9Qms1KF6qrzPkPTeaG349kxD6sBqBcX6M438aJ+l/f3GxyQVy7heCYVsHKHxgepXcRrs19t1vYWRBGqbHQHxFdeuItEgOYMCtgMPWiNesvYiXVThWC7qZCAvVlqQN4b2M+VQaOZXRHyuh+8E/UHyVZZ3zrtDeZWCXcB2V9mohl/oTuE96u5zE0mk+T03wko6XZ+Fj5EpmGHLDhCQj/fHaq6+lydtqlrZ4H5uUJiSLyrDkq45x5oC9EUpva3uBMlJJHLJp3ppwqyOtzyhyBfh3XlpWjFUaehJIU/0ql3QX5KlYNhGy0AWs7nRHtDC5JWwUluOYl21h8z7GUYfMkSIKe4aby30e+B/lNFosjwEQv43fP1h5J4LgzQmE5tVEctsB5XM6Hb8TMryGu44IqZ8kJqxjjeGmU4BRr0ZVCx8yjW4hHI8lQ5IRz6Qo1G1xIa82beARSoyggboCmcOSm5dOzx86xWcDHebxPPc/s8174oPeNL8GEynDLsR2pcXVuzylPOxSbMDHGit6ritkE5tkIL8gZ4MK1XcuYkohMFO6mrm/3EQUCbqDZtcFKDXWCgYaWajfVQv41qhmWa3j441z2/ptXR6SIe2FrVBS1pygd6panwzISjAeIcceXqjNN2/8Mvv6AKax57nYKnm1vg6S80=
