default_platform(:android)

platform :android do

  desc "Submit a new Dev Build to Firebase App Distribution"
  lane :dev do
    firebase_app_distribution(
          app: "1:167887597085:android:30e530cb463d95cc",
          apk_path: "app/build/outputs/apk/dev/app-dev.apk",
          groups: "dev",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

end
